management:
    endpoints:
     web:
      exposure:
       include: "health,info,beans,caches"   

spring:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: "update"
  datasource:
    url: "jdbc:h2:tcp://localhost/~/test"
    username: "sa"
    password: "" 
  batch:
    jdbc:
      initialize-schema: "never"
      continue-on-error: false
    job:
      enabled: false
logging:
  level:
    org.springframework.batch: DEBUG
    org.springframework.jdbc: DEBUG